### ISSUE TITLE
[0.4.2] Unable to adjust wings

### ISSUE THREAD

**Issue by Chryseus** [tetraflon/B9-PWings-Modified#5]
Mod version: 0.4.2
Game version: 1.11.1

When moving / placing procedural wings it eventually breaks, the handles vanish and any adjustment made via the inputs are ignored, a restart is required to fix it.
The log file is flooded with the following exception beginning at line 315 839:

`NullReferenceException
  at (wrapper managed-to-native) UnityEngine.GameObject.get_transform(UnityEngine.GameObject)
  at WingProcedural.WingProcedural.DetachHandles () [0x00001] in <39a0fa00ba564608afed94e7fcab4a6a>:0 
  at WingProcedural.WingProcedural.UpdateHandleGizmos () [0x00017] in <39a0fa00ba564608afed94e7fcab4a6a>:0 
  at WingProcedural.WingProcedural.Update () [0x00051] in <39a0fa00ba564608afed94e7fcab4a6a>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)`

[Player.log.zip](https://github.com/tetraflon/B9-PWings-Modified/files/6097707/Player.log.zip)
[modlist.txt](https://github.com/tetraflon/B9-PWings-Modified/files/6097711/modlist.txt)

**Comment by tetraflon** [comment]
The problem may be resolved in the next release.

**Comment by tetraflon** [comment]
confirmed, is this happened every time you switch to edit other PW by pressing j without exit editing the one you are editing?

**Comment by tetraflon** [comment]
Howdy, this is a long-known issue, still haven't got any method to prevent Unity from accidentally delete those transforms of the handles. And it is very hard to know whether the modifications work because the problem occurred on a random basis.

**Comment by tetraflon** [comment]
If you have got any method that can 100% to reproduce the issue, drop a comment below.

**Comment by Chryseus** [comment]
Yeah I'm having trouble reproducing it now, I know it occured when editing two different wings but I can't seem to get it to happen again, I'll close this for now until I can find a way to reliabily reproduce it.
